// In cli/src/constants.rs

pub const CUSTOM_OCI_IMAGE_OPTION: &str = "[ Type Custom OCI Image ]";

// (shortname, full_url)
pub const DISTROBOX_IMAGES: &[(&str, &str)] = &[
    // --- Toolbox Images ---
    ("almalinux-toolbox:8", "quay.io/toolbx-images/almalinux-toolbox:8"),
    ("almalinux-toolbox:9", "quay.io/toolbx-images/almalinux-toolbox:9"),
    ("almalinux-toolbox:latest", "quay.io/toolbx-images/almalinux-toolbox:latest"),
    ("alpine-toolbox:3.16", "quay.io/toolbx-images/alpine-toolbox:3.16"),
    ("alpine-toolbox:3.17", "quay.io/toolbx-images/alpine-toolbox:3.17"),
    ("alpine-toolbox:3.18", "quay.io/toolbx-images/alpine-toolbox:3.18"),
    ("alpine-toolbox:3.19", "quay.io/toolbx-images/alpine-toolbox:3.19"),
    ("alpine-toolbox:3.20", "quay.io/toolbx-images/alpine-toolbox:3.20"),
    ("alpine-toolbox:edge", "quay.io/toolbx-images/alpine-toolbox:edge"),
    ("alpine-toolbox:latest", "quay.io/toolbx-images/alpine-toolbox:latest"),
    ("amazonlinux-toolbox:2", "quay.io/toolbx-images/amazonlinux-toolbox:2"),
    ("amazonlinux-toolbox:2023", "quay.io/toolbx-images/amazonlinux-toolbox:2023"),
    ("amazonlinux-toolbox:latest", "quay.io/toolbx-images/amazonlinux-toolbox:latest"),
    ("arch-toolbox:latest", "quay.io/toolbx/arch-toolbox:latest"),
    ("bazzite-arch:latest", "ghcr.io/ublue-os/bazzite-arch:latest"),
    ("bazzite-arch-gnome:latest", "ghcr.io/ublue-os/bazzite-arch-gnome:latest"),
    ("centos-toolbox:stream8", "quay.io/toolbx-images/centos-toolbox:stream8"),
    ("centos-toolbox:stream9", "quay.io/toolbx-images/centos-toolbox:stream9"),
    ("centos-toolbox:latest", "quay.io/toolbx-images/centos-toolbox:latest"),
    ("debian-toolbox:10", "quay.io/toolbx-images/debian-toolbox:10"),
    ("debian-toolbox:11", "quay.io/toolbx-images/debian-toolbox:11"),
    ("debian-toolbox:12", "quay.io/toolbx-images/debian-toolbox:12"),
    ("debian-toolbox:testing", "quay.io/toolbx-images/debian-toolbox:testing"),
    ("debian-toolbox:unstable", "quay.io/toolbx-images/debian-toolbox:unstable"),
    ("debian-toolbox:latest", "quay.io/toolbx-images/debian-toolbox:latest"),
    ("fedora-toolbox:37", "registry.fedoraproject.org/fedora-toolbox:37"),
    ("fedora-toolbox:38", "registry.fedoraproject.org/fedora-toolbox:38"),
    ("fedora-toolbox:39", "registry.fedoraproject.org/fedora-toolbox:39"),
    ("fedora-toolbox:40", "registry.fedoraproject.org/fedora-toolbox:40"),
    ("fedora-toolbox:41", "quay.io/fedora/fedora-toolbox:41"),
    ("fedora-toolbox:rawhide", "quay.io/fedora/fedora-toolbox:rawhide"),
    ("opensuse-distrobox:latest", "registry.opensuse.org/opensuse/distrobox:latest"),
    ("rhel-toolbox:8", "registry.access.redhat.com/ubi8/toolbox"),
    ("rhel-toolbox:9", "registry.access.redhat.com/ubi9/toolbox"),
    ("rockylinux-toolbox:8", "quay.io/toolbx-images/rockylinux-toolbox:8"),
    ("rockylinux-toolbox:9", "quay.io/toolbx-images/rockylinux-toolbox:9"),
    ("rockylinux-toolbox:latest", "quay.io/toolbx-images/rockylinux-toolbox:latest"),
    ("ubuntu-toolbox:16.04", "quay.io/toolbx/ubuntu-toolbox:16.04"),
    ("ubuntu-toolbox:18.04", "quay.io/toolbx/ubuntu-toolbox:18.04"),
    ("ubuntu-toolbox:20.04", "quay.io/toolbx/ubuntu-toolbox:20.04"),
    ("ubuntu-toolbox:22.04", "quay.io/toolbx/ubuntu-toolbox:22.04"),
    ("ubuntu-toolbox:24.04", "quay.io/toolbx/ubuntu-toolbox:24.04"),
    ("ubuntu-toolbox:latest", "quay.io/toolbx/ubuntu-toolbox:latest"),
    ("wolfi-toolbox:latest", "quay.io/toolbx-images/wolfi-toolbox:latest"),
    ("ublue-bluefin-cli", "ghcr.io/ublue-os/bluefin-cli"),
    ("ublue-ubuntu-toolbox", "ghcr.io/ublue-os/ubuntu-toolbox"),
    ("ublue-fedora-toolbox", "ghcr.io/ublue-os/fedora-toolbox"),
    ("ublue-wolfi-toolbox", "ghcr.io/ublue-os/wolfi-toolbox"),
    ("ublue-arch-distrobox", "ghcr.io/ublue-os/arch-distrobox"),
    ("ublue-powershell-toolbox", "ghcr.io/ublue-os/powershell-toolbox"),

    // --- Standard Images ---
    ("almalinux:8", "docker.io/library/almalinux:8"),
    ("almalinux:9", "docker.io/library/almalinux:9"),
    ("alpine:3.15", "docker.io/library/alpine:3.15"),
    ("alpine:3.16", "docker.io/library/alpine:3.16"),
    ("alpine:3.17", "docker.io/library/alpine:3.17"),
    ("alpine:3.18", "docker.io/library/alpine:3.18"),
    ("alpine:3.19", "docker.io/library/alpine:3.19"),
    ("alpine:3.20", "docker.io/library/alpine:3.20"),
    ("alpine:edge", "docker.io/library/alpine:edge"),
    ("alpine:latest", "docker.io/library/alpine:latest"),
    ("amazonlinux:1", "public.ecr.aws/amazonlinux/amazonlinux:1"),
    ("amazonlinux:2", "public.ecr.aws/amazonlinux/amazonlinux:2"),
    ("amazonlinux:2023", "public.ecr.aws/amazonlinux/amazonlinux:2023"),
    ("archlinux:latest", "docker.io/library/archlinux:latest"),
    ("blackarch:latest", "docker.io/blackarchlinux/blackarch:latest"),
    ("centos:stream8", "quay.io/centos/centos:stream8"),
    ("centos:stream9", "quay.io/centos/centos:stream9"),
    ("wolfi-base:latest", "cgr.dev/chainguard/wolfi-base:latest"),
    ("clearlinux:latest", "docker.io/library/clearlinux:latest"),
    ("clearlinux:base", "docker.io/library/clearlinux:base"),
    ("crystallinux:latest", "registry.gitlab.com/crystal-linux/misc/docker:latest"),
    ("debian:7", "docker.io/debian/eol:wheezy"), // wheezy
    ("debian:10", "docker.io/library/debian:buster"), // buster
    ("debian:11-backports", "docker.io/library/debian:bullseye-backports"),
    ("debian:12-backports", "docker.io/library/debian:bookworm-backports"),
    ("debian:stable-backports", "docker.io/library/debian:stable-backports"),
    ("debian:testing", "docker.io/library/debian:testing"),
    ("debian:testing-backports", "docker.io/library/debian:testing-backports"),
    ("debian:unstable", "docker.io/library/debian:unstable"),
    ("deepin:20", "docker.io/linuxdeepin/apricot"), // apricot
    ("deepin:23", "docker.io/linuxdeepin/deepin:beige"), // beige
    ("fedora:36", "quay.io/fedora/fedora:36"),
    ("fedora:37", "quay.io/fedora/fedora:37"),
    ("fedora:38", "quay.io/fedora/fedora:38"),
    ("fedora:39", "quay.io/fedora/fedora:39"),
    ("fedora:40", "quay.io/fedora/fedora:40"),
    ("fedora:41", "quay.io/fedora/fedora:41"),
    ("fedora:rawhide", "quay.io/fedora/fedora:rawhide"),
    ("gentoo:latest", "docker.io/gentoo/stage3:latest"),
    ("kdeneon:latest", "invent-registry.kde.org/neon/docker-images/plasma:latest"),
    ("kali-rolling:latest", "docker.io/kalilinux/kali-rolling:latest"),
    ("mint:21.1", "docker.io/linuxmintd/mint21.1-amd64"),
    ("neurodebian:nd100", "docker.io/library/neurodebian:nd100"),
    ("opensuse:leap", "registry.opensuse.org/opensuse/leap:latest"),
    ("opensuse:tumbleweed", "registry.opensuse.org/opensuse/tumbleweed:latest"),
    ("opensuse:toolbox", "registry.opensuse.org/opensuse/toolbox:latest"),
    ("oraclelinux:7", "container-registry.oracle.com/os/oraclelinux:7"),
    ("oraclelinux:7-slim", "container-registry.oracle.com/os/oraclelinux:7-slim"),
    ("oraclelinux:8", "container-registry.oracle.com/os/oraclelinux:8"),
    ("oraclelinux:8-slim", "container-registry.oracle.com/os/oraclelinux:8-slim"),
    ("oraclelinux:9", "container-registry.oracle.com/os/oraclelinux:9"),
    ("oraclelinux:9-slim", "container-registry.oracle.com/os/oraclelinux:9-slim"),
    ("rhel-ubi:7", "registry.access.redhat.com/ubi7/ubi"),
    ("rhel-ubi:8", "registry.access.redhat.com/ubi8/ubi"),
    ("rhel-ubi:8-init", "registry.access.redhat.com/ubi8/ubi-init"),
    ("rhel-ubi:8-minimal", "registry.access.redhat.com/ubi8/ubi-minimal"),
    ("rhel-ubi:9", "registry.access.redhat.com/ubi9/ubi"),
    ("rhel-ubi:9-init", "registry.access.redhat.com/ubi9/ubi-init"),
    ("rhel-ubi:9-minimal", "registry.access.redhat.com/ubi9/ubi-minimal"),
    ("rockylinux:8", "quay.io/rockylinux/rockylinux:8"),
    ("rockylinux:8-minimal", "quay.io/rockylinux/rockylinux:8-minimal"),
    ("rockylinux:9", "quay.io/rockylinux/rockylinux:9"),
    ("rockylinux:latest", "quay.io/rockylinux/rockylinux:latest"),
    ("slackware:current", "docker.io/vbatts/slackware:current"),
    ("steamos:latest", "ghcr.io/linuxserver/steamos:latest"),
    ("ubuntu:14.04", "docker.io/library/ubuntu:14.04"),
    ("ubuntu:16.04", "docker.io/library/ubuntu:16.04"),
    ("ubuntu:18.04", "docker.io/library/ubuntu:18.04"),
    ("ubuntu:20.04", "docker.io/library/ubuntu:20.04"),
    ("ubuntu:22.04", "docker.io/library/ubuntu:22.04"),
    ("ubuntu:24.04", "docker.io/library/ubuntu:24.04"),
    ("vanillaos:vso", "ghcr.io/vanilla-os/vso:main"),
    ("void-glibc:latest", "ghcr.io/void-linux/void-glibc-full:latest"),
    ("void-musl:latest", "ghcr.io/void-linux/void-musl-full:latest"),
];